app_token: "cQovpGcdUT1CSzgYk0KPYdAI0"
user_agent: "OpenDataNetwork.com"
timeout_ms: 5000

cache_options:
  expires: 43200

odn_api:
  base: "https://api.opendatanetwork.com"
  entity_lookup_endpoint: "/entity/v1"
  data_availability_endpoint: "/data/v1/availability"
  data_constraint_endpoint: "/data/v1/constraint/{0}"
  data_values_endpoint: "/data/v1/values"

  related_child_endpoint: "/entity/v1/child"
  related_parent_endpoint: "/entity/v1/parent"
  related_peer_endpoint: "/entity/v1/peer"
  related_sibling_endpoint: "/entity/v1/sibling"

  search_dataset_endpoint: "/search/v1/dataset"
  search_question_endpoint: "/search/v1/question"

  map_new_url: "/data/v1/map/new"

autocomplete:
  complete_max_options: 100
  separator: ":"
  shown_options: 5
  url:
    type: "/suggest/v1/${type}"
  wait_ms: 150

related_entity_count: 5
question_count: 10
n_relatives: 5

mobile_width: 800
scroll_threshold: 1000

regions:
  names:
    region.nation: "Nation"
    region.region: "Region"
    region.division: "Division"
    region.state: "State"
    region.county: "County"
    region.msa: "Metro Area"
    region.place: "Place"
    region.zip_code: "ZIP Code"
    region.township: "Township"

  plural_names:
    region.nation: "Nations"
    region.region: "Regions"
    region.division: "Divisions"
    region.state: "States"
    region.county: "Counties"
    region.msa: "Metro Areas"
    region.place: "Places"
    region.zip_code: "ZIP Codes"
    region.township: "Townships"

catalog:
  api: "http://api.us.socrata.com/api/catalog/v1"
  dataset_summary_url: "https://{0}/api/views/{1}.json"
  dataset_migrations_url: "https://{0}/api/migrations/{1}.json"

  default_metadata:
    description: ""
    icon: "fa-database"

datasets:
  roster: "https://odn.data.socrata.com/resource/czuf-rtrf.json"
  regions: "https://odn.data.socrata.com/resource/czuf-rtrf.json"

charts:
  options:
    chartArea:
      left: 80
      width: "100%"
    colors:
      - "#2980b9"
      - "#ee3b3b"
      - "#3bdbee"
      - "#ff9900"
      - "#109618"
      - "#0099c6"
      - "#dd4477"
      - "#66aa00"
      - "#b82e2e"
      - "#316395"
    cssClassNames:
      headerCell: "header-cell"
      headerRow: "header-row"
      tableCell: "table-cell"
    curveType: "function"
    height: 300
    legend:
      position : "top"
    lineWidth: 2
    pointShape: "square"
    pointSize: 8
    focusTarget: "category"

maps:
  update_wait: 200
  css_id: "leaflet-map"
  mapbox:
    token: "pk.eyJ1IjoibGFuZWFhc2VuIiwiYSI6ImYxZjExYmYzOTMxYzgyZTc2NDY0NDBmNDNmZmEwYWM3In0.uy5ta6EsSEZggkVQHo2ygw"
    label_layer_id: "socrata-apps.cb421623"
    base_layer_id: "socrata-apps.af2cc4ed"

  map_options:
    minZoom: 3.0
    maxZoom: 18.0
    zoomControl: false
    attributionControl: false
    scrollWheelZoom: false
    bounceAtZoomLimits: false

  zoom_control: true
  zoom_control_options:
    position: "topleft"

  initial_zoom_options:
    animate: false
    maxZoom: 10.0
    padding: [140, 140]

  poi_zoom: 11.0
  poi_wait_ms: 100

  base_style:
    fill: true
    fillOpacity: 0.35
    stroke: true
    color: "#2c3e50"
    weight: 1
    opacity: 1

  selected_style:
    weight: 6
    dashArray: "4, 8"
    lineCap: "round"

  legend_opacity: 0.5
  tooltip_padding: 16

  popup_options:
    closeButton: true
    closeOnClick: false

variables:
  finance.michigan_debt:
    charts:
      - id: finance.michigan_debt.debt_service.chart
        type: line
        name: Debt Service
        variables:
          - finance.michigan_debt.debt_service
        options:
          vAxis:
            format: '#,###.##%'
      - id: finance.michigan_debt.debt_long_term.chart
        type: line
        name: Long Term Debt
        variables:
          - finance.michigan_debt.debt_long_term
      - id: finance.michigan_debt.long_term_debt_revenue.chart
        type: line
        name: Long Term Debt Revenue
        variables:
          - finance.michigan_debt.long_term_debt_revenue
        options:
          vAxis:
            format: '#,###.##%'
      - id: finance.michigan_debt.debt_health.chart
        type: line
        name: Debt Per Capita
        variables:
          - finance.michigan_debt.debt_health
  finance.michigan_expenditures:
    charts:
      - id: finance.michigan_expenditures.public_safety_expenditures.chart
        type: line
        name: Total Public Safety Fund Expenditures
        variables:
          - finance.michigan_expenditures.public_safety_expenditures
      - id: finance.michigan_expenditures.total_general_fund_expenditures.chart
        type: line
        name: Total General Fund Expenditures
        variables:
          - finance.michigan_expenditures.total_general_fund_expenditures
  finance.michigan_general_fund:
    charts:
      - id: finance.michigan_general_fund.general_fund_balance.chart
        type: line
        name: General Fund Balance
        variables:
          - finance.michigan_general_fund.general_fund_balance
      - id: finance.michigan_general_fund.liquidity_ratio.chart
        type: line
        name: Liquidity Ratio
        variables:
          - finance.michigan_general_fund.liquidity_ratio
      - id: finance.michigan_general_fund.general_fund_unrestricted_balance.chart
        type: line
        name: General Fund Unrestricted Balance
        variables: 
          - finance.michigan_general_fund.general_fund_unrestricted_balance
      - id: finance.michigan_general_fund.general_fund_health.chart
        type: line
        name: General Fund Balance Per Capita
        variables:
          - finance.michigan_general_fund.general_fund_health
  finance.michigan_pensions:
    charts:
      - id: finance.michigan_pensions.unfunded_pension_liability.chart
        type: line
        name: Unfunded Pension Liability
        variables:
          - finance.michigan_pensions.unfunded_pension_liability
      - id: finance.michigan_pensions.pension_health.chart
        type: line
        name: Unfunded Pension Liability Per Capita
        variables:
          - finance.michigan_pensions.pension_health
  finance.michigan_property_tax:
    charts:
      - id: finance.michigan_property_tax.debt_taxable_value.chart
        type: line
        name: Debt as % of Taxable Value
        variables:
          - finance.michigan_property_tax.debt_taxable_value
        options:
          vAxis:
            format: '#,###.##%'
      - id: finance.michigan_property_tax.total_taxable_value.chart
        type: line
        name: Total Taxable Value
        variables:
          - finance.michigan_property_tax.total_taxable_value
      - id: finance.michigan_property_tax.property_tax_health.chart
        type: line
        name: Total Taxable Value Per Capita
        variables:
          - finance.michigan_property_tax.property_tax_health
  finance.michigan_revenues:
    charts:
      - id: finance.michigan_revenues.total_general_fund_revenue.chart
        type: line
        name: Total General Fund Revenue
        variables:
          - finance.michigan_revenues.total_general_fund_revenue
      - id: finance.michigan_revenues.unrestricted_revenue.chart
        type: line
        name: Unrestricted Revenue
        variables:
          - finance.michigan_revenues.unrestricted_revenue
  crime.fbi_ucr:
    charts:
      - id: crime.fbi_ucr.count.chart
        type: bar
        constraint:
          year: '2014'
        name: Crime Incident Count
        options:
          chartArea:
            left: 270
          height: 450
        mobileOptions:
          chartArea:
            left: 100
        variables:
          - crime.fbi_ucr.count
        exclude:
          - All Crimes
      - id: crime.fbi_ucr.rate.chart
        type: bar
        constraint:
          year: '2014'
        name: 'Crime Incident Rate per 100,000 People'
        options:
          chartArea:
            left: 270
          height: 450
        mobileOptions:
          chartArea:
            left: 100
        variables:
          - crime.fbi_ucr.rate
        exclude:
          - All Crimes
  demographics.population:
    charts:
      - id: demographics.population.count.chart
        type: line
        forecast: 5
        name: Population
        variables:
          - demographics.population.count
      - id: demographics.population.change.chart
        type: line
        name: Population Change
        variables:
          - demographics.population.change
  geographic.population:
    charts:
      - id: geographic.population.density.chart
        type: line
        forecast: 5
        name: Population Density
        variables:
          - geographic.population.density
  geographic.area:
    charts:
      - id: geographic.area.land_area.chart
        type: table
        constraint:
        year: '2014'
        forecast: 5
        name: Land Area
        variables:
          - geographic.area.land_area
      - id: geographic.area.water_area.chart
        type: table
        year: '2014'
        name: Water Area
        variables:
          - geographic.area.water_area
  economy.consumption:
    charts:
      - id: economy.consumption.personal_consumption_expenditures.chart
        type: line
        forecast: 5
        name: Personal Consumption Expenditures over Time (Millions of USD)
        variables:
          - economy.consumption.personal_consumption_expenditures
      - id: economy.consumption.expenditures_percent_change.chart
        type: line
        name: Change in Personal Consumption Expenditures over Time
        variables:
          - economy.consumption.expenditures_percent_change
  economy.personal_income:
    charts:
      - id: economy.personal_income.annual_personal_income.chart
        type: line
        forecast: 5
        name: Annual Personal Income in US$
        variables:
          - economy.personal_income.annual_personal_income
  economy.cost_of_living:
    charts:
      - id: economy.cost_of_living.index.chart
        type: table
        constraint:
          year: '2013'
        name: Cost of Living
        variables:
          - economy.cost_of_living.index
      - id: economy.cost_of_living.index.all.chart
        type: line
        constraint:
          component: All
        forecast: 5
        name: Overall Cost of Living
        variables:
          - economy.cost_of_living.index
      - id: economy.cost_of_living.index.goods.chart
        type: line
        constraint:
          component: Goods
        forecast: 5
        name: Cost of Goods
        variables:
          - economy.cost_of_living.index
      - id: economy.cost_of_living.index.rents.chart
        type: line
        constraint:
          component: Rents
        forecast: 5
        name: Cost of Rents
        variables:
          - economy.cost_of_living.index
      - id: economy.cost_of_living.index.other.chart
        type: line
        constraint:
          component: Other
        forecast: 5
        name: Other Costs
        variables:
          - economy.cost_of_living.index
  economy.gdp:
    charts:
      - id: economy.gdp.per_capita_gdp.chart
        type: line
        forecast: 5
        description: Real (inflation adjusted) GDP per Capita over time.
        name: GDP
        variables:
          - economy.gdp.per_capita_gdp
      - id: economy.gdp.per_capita_gdp_percent_change.chart
        type: line
        description: Annual change in real GDP.
        name: Change in GDP
        variables:
          - economy.gdp.per_capita_gdp_percent_change
  economy.state_exports:
    charts:
      - id: economy.state_exports.all_goods_timeline.chart
        type: line
        name: Value of All Goods
        constraint:
          month: 'Total'
        variables:
          - economy.state_exports.all_goods
      - id: economy.state_exports.all_goods_seasonality.chart
        type: column
        name: Manufacturing Seasonality
        constraint:
          year: 2015
        exclude:
          - Total
        variables:
          - economy.state_exports.all_goods
      - id: economy.state_exports.classification.chart
        type: bar
        name: Types of Goods
        constraint:
          month: 'Total'
          year: '2016'
        variables:
          - economy.state_exports.manufactured
          - economy.state_exports.non_manufactured
  education.classroom_statistics:
    charts:
      - id: education.classroom_statistics.chart
        type: line
        forecast: 7
        name: Student Teacher Ratio
        variables:
          - education.classroom_statistics.student-teacher-ratio
  education.graduation_rates:
    charts:
      - id: education.education.chart
        type: table
        constraint:
          year: '2013'
        name: Graduation Rates
  education.education_expenditures:
    charts:
      - id: education.education_expenditures.capital-expenditures.chart
        type: line
        forecast: 7
        name: Capital Expenditures
        variables:
          - education.education_expenditures.capital-expenditures
      - id: education.education_expenditures.capital-expenditures-per-student.chart
        type: line
        forecast: 7
        name: Capital Expenditures Per Student
        variables:
          - education.education_expenditures.capital-expenditures-per-student
      - id: education.education_expenditures.administration-salaries.chart
        type: line
        forecast: 7
        name: Administration Salaries
        variables:
          - education.education_expenditures.administration-salaries
      - id: >-
          education.education_expenditures.administration-salaries-per-student.chart
        type: line
        forecast: 7
        name: Administration Salaries Per Student
        variables:
          - education.education_expenditures.administration-salaries-per-student
      - id: education.education_expenditures.instruction-salaries.chart
        type: line
        forecast: 7
        name: Instruction Salaries
        variables:
          - education.education_expenditures.instruction-salaries
      - id: education.education_expenditures.instruction-salaries-per-student.chart
        type: line
        forecast: 7
        name: Instruction Salaries Per Student
        variables:
          - education.education_expenditures.instruction-salaries-per-student
  health.health_insurance:
    charts:
      - id: health.health_insurance.pctui.chart
        type: line
        constraint:
          age: 18 to 64
          race: All races
          sex: Both sexes
          income: All income levels
        name: Percent Uninsured
        forecast: 5
        variables:
          - health.health_insurance.pctui
      - id: health.health_insurance.income.chart
        type: column
        constraint:
          year: '2014'
          age: 18 to 64
          race: All races
          sex: Both sexes
        name: Percent Uninsured by Income Level
        variables:
          - health.health_insurance.pctui
      - id: health.health_insurance.race.chart
        type: bar
        constraint:
          year: '2014'
          age: 18 to 64
          sex: Both sexes
          income: All income levels
        name: Percent Uninsured by Race
        variables:
          - health.health_insurance.pctui
  health.environmental_health:
    charts:
      - id: health.environmental_health.chart
        type: column
        constraint:
          year: '2015'
        name: Median Environmental Health Hazard Index
        variables:
          - health.environmental_health.env-health-idx-median
  health.health_behaviors:
    charts:
      - id: health.health_behaviors.chart
        type: table
        constraint:
          year: '2015'
        name: Health Behaviors
        options:
          height: 400
        variables:
          - health.health_behaviors
  jobs.earnings:
    charts:
      - id: jobs.earnings.gender.chart
        type: table
        constraint:
          year: '2013'
        name: Earnings and Gender
        variables:
          - jobs.earnings.median_earnings
          - jobs.earnings.female_median_earnings
          - jobs.earnings.male_median_earnings
      - id: jobs.earnings.education.chart
        type: stepped-area
        constraint:
          year: '2013'
        name: Earnings and Education
        options:
          areaOpacity: 0
        variables:
          - jobs.earnings.median_earnings_less_than_high_school
          - jobs.earnings.median_earnings_high_school
          - jobs.earnings.median_earnings_some_college_or_associates
          - jobs.earnings.median_earnings_bachelor_degree
          - jobs.earnings.median_earnings_graduate_or_professional_degree
  jobs.job_proximity:
    charts:
      - id: jobs.job_proximity
        type: column
        constraint:
          year: '2015'
        name: Median Jobs Proximity Index
        variables:
          - jobs.job_proximity.jobs-prox-idx-median
  jobs.occupations:
    charts:
      - id: jobs.occupations.chart
        type: table
        constraint:
          year: '2013'
        name: Occupations
        variables:
          - jobs.occupations.percent_employed
